theme: jekyll-theme-architect
title: Shopping Predictions
description: In this project, our team used machine learning to predict the best time in the next x days to buy a certain product off of Amazon.
